### ISSUE TITLE
Minimal AWS Permissions

### ISSUE THREAD

**Issue by maxbeatty** [auth0-extensions/auth0-logs-to-cloudwatch#2]
Are the minimal AWS permissions necessary just `logs:DescribeLogGroups`, `logs:DescribeLogStreams`, and `logs:PutLogEvents`?

**Comment by maxbeatty** [comment]
It'd be great hear from someone at Auth0 and to get these permissions documented

**Comment by maxbeatty** [comment]
I’m happy to help update the documentation if someone from @auth0-extensions would weigh in with the official definitions.

**Comment by fyockm** [comment]
@maxbeatty - @ShayMe21 *is* a member of @auth0-extensions. he's correct that these 2 are required:

```
"logs:PutLogEvents",
"logs:DescribeLogStreams"
```

`logs:DescribeLogGroups` is not necessary

since this repo is actually being archived, we'll be sure add documentation for the Logs to Cloudwatch Extension [here](https://auth0.com/docs/extensions), with those instructions.
